DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS map;
DROP TABLE IF EXISTS node;
DROP TABLE IF EXISTS edge;
DROP TABLE IF EXISTS user_map;
DROP TABLE IF EXISTS map_node;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL
);

CREATE TABLE map (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE user_map (
    user_ref INTEGER,
    map_ref INTEGER
);